artifact_uri: file:///D:/Training/03 Projects/03) ML Projects/Linear/AirfarePrediction/your_tracking_uri/0/144d2ecfb4984aaa9e4f9b508bc0aaad/artifacts
end_time: 1738759150897
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 144d2ecfb4984aaa9e4f9b508bc0aaad
run_name: ElasticNet
run_uuid: 144d2ecfb4984aaa9e4f9b508bc0aaad
source_name: ''
source_type: 4
source_version: ''
start_time: 1738759146107
status: 3
tags: []
user_id: SHIVRAJ SHINDE
