artifact_uri: file:///D:/Training/03 Projects/03) ML Projects/Linear/AirfarePrediction/your_tracking_uri/0/aff071b5a1aa446b80af3f2cf02281e9/artifacts
end_time: 1738759067042
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: aff071b5a1aa446b80af3f2cf02281e9
run_name: ElasticNet
run_uuid: aff071b5a1aa446b80af3f2cf02281e9
source_name: ''
source_type: 4
source_version: ''
start_time: 1738759061931
status: 3
tags: []
user_id: SHIVRAJ SHINDE
