artifact_location: file:///D:/Training/03 Projects/03) ML Projects/Linear/AirfarePrediction/your_tracking_uri/0
creation_time: 1738759015230
experiment_id: '0'
last_update_time: 1738759015230
lifecycle_stage: active
name: Default
