artifact_uri: file:///D:/Training/03 Projects/03) ML Projects/Linear/AirfarePrediction/your_tracking_uri/0/0fc9394fbbe74f819463b064e44b8b36/artifacts
end_time: 1738759023078
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0fc9394fbbe74f819463b064e44b8b36
run_name: ElasticNet
run_uuid: 0fc9394fbbe74f819463b064e44b8b36
source_name: ''
source_type: 4
source_version: ''
start_time: 1738759016042
status: 3
tags: []
user_id: SHIVRAJ SHINDE
